try {
    const a = 2
    const b = a.toUpperCase()
} catch (error) {
    console.error(`Ocorreu um erro: `, error.message)
}